/**
 * Created by tiwenleo on 17/10/6.
 */
const loginApi = 'users/';
export default loginApi;


//user
// {
//   "login": "Leotw",
//   "id": 12053096,
//   "avatar_url": "https://avatars2.githubusercontent.com/u/12053096?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/Leotw",
//   "html_url": "https://github.com/Leotw",
//   "followers_url": "https://api.github.com/users/Leotw/followers",
//   "following_url": "https://api.github.com/users/Leotw/following{/other_user}",
//   "gists_url": "https://api.github.com/users/Leotw/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/Leotw/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/Leotw/subscriptions",
//   "organizations_url": "https://api.github.com/users/Leotw/orgs",
//   "repos_url": "https://api.github.com/users/Leotw/repos",
//   "events_url": "https://api.github.com/users/Leotw/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/Leotw/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": "天空",
//   "company": "PingAn",
//   "blog": "",
//   "location": "Shanghai",
//   "email": null,
//   "hireable": null,
//   "bio": null,
//   "public_repos": 15,
//   "public_gists": 0,
//   "followers": 46,
//   "following": 55,
//   "created_at": "2015-04-21T15:34:28Z",
//   "updated_at": "2017-09-28T05:59:25Z"
// }

//repo
// [{
//   "id": 10073359,
//   "name": "homebrew-nginx",
//   "full_name": "Homebrew/homebrew-nginx",
//   "owner": {
//   "login": "Homebrew",
//     "id": 1503512,
//     "avatar_url": "https://avatars2.githubusercontent.com/u/1503512?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Homebrew",
//     "html_url": "https://github.com/Homebrew",
//     "followers_url": "https://api.github.com/users/Homebrew/followers",
//     "following_url": "https://api.github.com/users/Homebrew/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Homebrew/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Homebrew/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Homebrew/subscriptions",
//     "organizations_url": "https://api.github.com/users/Homebrew/orgs",
//     "repos_url": "https://api.github.com/users/Homebrew/repos",
//     "events_url": "https://api.github.com/users/Homebrew/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Homebrew/received_events",
//     "type": "Organization",
//     "site_admin": false
// },
//   "private": false,
//   "html_url": "https://github.com/Homebrew/homebrew-nginx",
//   "description": ":fire_engine: Community NGINX tap for custom modules",
//   "fork": false,
//   "url": "https://api.github.com/repos/Homebrew/homebrew-nginx",
//   "forks_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/forks",
//   "keys_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/keys{/key_id}",
//   "collaborators_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/collaborators{/collaborator}",
//   "teams_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/teams",
//   "hooks_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/hooks",
//   "issue_events_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/issues/events{/number}",
//   "events_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/events",
//   "assignees_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/assignees{/user}",
//   "branches_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/branches{/branch}",
//   "tags_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/tags",
//   "blobs_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/git/blobs{/sha}",
//   "git_tags_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/git/tags{/sha}",
//   "git_refs_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/git/refs{/sha}",
//   "trees_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/git/trees{/sha}",
//   "statuses_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/statuses/{sha}",
//   "languages_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/languages",
//   "stargazers_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/stargazers",
//   "contributors_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/contributors",
//   "subscribers_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/subscribers",
//   "subscription_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/subscription",
//   "commits_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/commits{/sha}",
//   "git_commits_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/git/commits{/sha}",
//   "comments_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/comments{/number}",
//   "issue_comment_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/issues/comments{/number}",
//   "contents_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/contents/{+path}",
//   "compare_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/compare/{base}...{head}",
//   "merges_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/merges",
//   "archive_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/{archive_format}{/ref}",
//   "downloads_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/downloads",
//   "issues_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/issues{/number}",
//   "pulls_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/pulls{/number}",
//   "milestones_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/milestones{/number}",
//   "notifications_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/notifications{?since,all,participating}",
//   "labels_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/labels{/name}",
//   "releases_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/releases{/id}",
//   "deployments_url": "https://api.github.com/repos/Homebrew/homebrew-nginx/deployments",
//   "created_at": "2013-05-15T07:33:45Z",
//   "updated_at": "2017-10-02T17:14:10Z",
//   "pushed_at": "2017-09-30T03:02:18Z",
//   "git_url": "git://github.com/Homebrew/homebrew-nginx.git",
//   "ssh_url": "git@github.com:Homebrew/homebrew-nginx.git",
//   "clone_url": "https://github.com/Homebrew/homebrew-nginx.git",
//   "svn_url": "https://github.com/Homebrew/homebrew-nginx",
//   "homepage": "",
//   "size": 591,
//   "stargazers_count": 296,
//   "watchers_count": 296,
//   "language": "Ruby",
//   "has_issues": true,
//   "has_projects": false,
//   "has_downloads": true,
//   "has_wiki": false,
//   "has_pages": true,
//   "forks_count": 109,
//   "mirror_url": null,
//   "open_issues_count": 11,
//   "forks": 109,
//   "open_issues": 11,
//   "watchers": 296,
//   "default_branch": "master"
// }]


